spring.application.name=lift
spring.datasource.url= jdbc:sqlserver://serverxareupreto.database.windows.net:1433;databaseName=LifitApp;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring.datasource.username=sa-xareu
spring.datasource.password=*123456HAS*
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# lift
#CONEXAO AZURE: jdbc:sqlserver://serverxareupreto.database.windows.net:1433;databaseName=LifitApp;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
#SENHA CONEXAO AZURE: *123456HAS*

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect